# Generated by Django 4.2 on 2023-05-06 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id comuna')),
                ('nombreComuna', models.CharField(max_length=50, verbose_name='Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id region')),
                ('nombreRegion', models.CharField(max_length=50, verbose_name='Region')),
            ],
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='ciudad_per',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='region_per',
        ),
        migrations.AddField(
            model_name='persona',
            name='Comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.comuna'),
        ),
        migrations.AddField(
            model_name='persona',
            name='Region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.region'),
        ),
    ]
