# Generated by Django 4.2 on 2023-05-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_contacto_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='correo_per',
            field=models.EmailField(max_length=30, verbose_name='Correo electronico'),
        ),
    ]
